<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="KinematicEngine\**\*.cs" />
    <Compile Remove="KinematicEngine\**\AssemblyInfo.cs" />
    <None    Remove="KinematicEngine\*.cs" />
    <ProjectReference Include="KinematicEngine\KinematicEngine.csproj"
                      Condition="Exists('KinematicEngine\KinematicEngine.csproj')" />
    <Compile Remove="TCPServer\**\*.cs" />
    <Compile Remove="TCPServer\**\AssemblyInfo.cs" />
    <None    Remove="TCPServer\*.cs" />
    <ProjectReference Include="TCPServer\TCPServer.csproj"
                      Condition="Exists('TCPServer\TCPServer.csproj')" />
    <PackageReference Include="Avalonia" Version="11.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

</Project>
